### ISSUE TITLE
Patch release?

### ISSUE THREAD

**Issue by cormullion** [LiorSinai/PolygonAlgorithms.jl#10]
Hi! Just wondering- do you think your v0.1.2 should actually be v0.2, since it’s not a patch release (bug fix) but the addition of new functionality?

I’m not an expert on semver, so I’m happy to learn more about it.

**Comment by LiorSinai** [comment]
Hi

Yes you're right. I've just reread the specs and I should have updated the minor version. 

I'll release a new version soon

**Comment by LiorSinai** [comment]
See Release v0.20 #11

**Comment by LiorSinai** [comment]
Released and merged.
